### ISSUE TITLE
How do I edit my rain.conf in the executable raind

### ISSUE THREAD

**Issue by 1000ml** [OBAViJEST/rain#9]
Hello,
I dont know how to setup my RCP password and other information in the rain.conf. on my Raspberry pi3 with Stretch.
Can you help me ?

**Comment by OBAViJEST** [comment]
(COPY ALL IN ONE GO):

cd ~
mkdir ~/.raind
cat << "CONFIG" >> ~/.raind/rain.conf

listen=1
rpcuser=LOCALUSER
rpcpassword=VERYSECURESUPERLONGSUPERSAFEPASSWORD
server=1
rpcallowip=192.168.0.*
gen=1

Let me know if this works :)

**Comment by 1000ml** [comment]
All good ! Thank you 👍
